export enum BlogThumbnail {
  Regex = 'regex',
  Npm = 'npm',
  Linux = 'linux',
  Browser = 'browser',
  MachineLearning = 'machine-learning',
  Docker = 'docker',
  NextJs = 'nextjs',
  Python = 'python',
  Sql = 'sql',
  Webpack = 'webpack',
  Apache = 'apache',
  Aws = 'aws',
}

export enum BlogTag {
  Regex = 'regex',
  Npm = 'npm',
  Linux = 'linux',
  Browser = 'browser',
  MachineLearning = 'machine-learning',
  Docker = 'docker',
  NextJs = 'nextjs',
  Python = 'python',
  Sql = 'sql',
  Webpack = 'webpack',
  BrowserApi = 'browser-api',
  Apache = 'apache',
  Aws = 'aws',
}
