import type { Shadows } from '@mui/material';

const PRIMARY_SHADOW = 'rgb(0 0 0 / 8%) 0 3px 10px 0';

export const shadows: Shadows = [
  'none',
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
];
